---
title: "P4 - Application"
author: "Group M04-04"
date: "2026-04-20"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
library(tidyverse)
library(tidyfinance)
library(scales)
library(ggrepel)
library(ggcorrplot)
```

```{r}
prices <- download_data(type = "stock_prices",
                         symbols = c("NVDA","NXPI","EPAM","BRK-B","PYPL","FDS","CAT","DAL","POOL",
            "AMZN","NCLH","CASY","LLY","BDX","CRL","GOOG","EA","PSKY",
            "WMT","CPB","EL","XOM","OXY","APA","LIN","MLM","MOS",
            "NEE","ATO","AES","WELL","SBA","ARE"),
                         start_date = "2016-01-01",
                         end_date = "2026-04-20")
  
```


```{r}
returns <- prices %>% 
  group_by(symbol) %>% 
  arrange(date) %>% 
  mutate(dailyret = log(adjusted_close/lag(adjusted_close))) %>% 
  select(symbol, date, dailyret) %>% 
  drop_na(dailyret)

```

```{r}
subset_returns <- returns %>% 
  filter(symbol %in% c("NVDA", "BRK-B", "AMZN", "LLY", "GOOG", "CAT"))

subset_returns %>% 
  ggplot(aes(x = dailyret)) +
  geom_histogram(bins = 100,
                 fill = "steelblue") +
  facet_wrap(~symbol, scales = "free") +
  labs(title = "Histogram over daily returns for AMZN, BRK-B, GOOG, LLY, and NVDA",
       x = "Return",
       y = "Frequency") +
  theme_minimal()
```
```{r}
subset_returns %>% 
  ggplot(aes(sample = dailyret)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  facet_wrap(~symbol, scales = "free") +
  labs(
    x = "Theoretical quantiles",
    y = "Sample quantiles"
  ) +
  theme_minimal()
```




```{r}
assets <- returns %>% 
  group_by(symbol) %>% 
  summarize(mu = mean(dailyret),
            sd = sd(dailyret))
assets <- assets %>% arrange(match(symbol, colnames(sigma)))
```

```{r}
assets %>% 
  ggplot(aes(x = sd*sqrt(252),
             y = mu*252,
             label = symbol)) +
  geom_point() +
  geom_text_repel() +
  scale_x_continuous(labels = percent) +
  scale_y_continuous(labels = percent) +
  labs(x = "Standard deviation",
       y = "Expected return") +
  theme_minimal()
```
```{r}
returns_wide <- returns %>% 
  pivot_wider(names_from = symbol,
              values_from = dailyret)

sigma_c <- returns_wide %>% 
  select(-date) %>% 
  cor(use = "pairwise.complete.obs")

sigma_c %>% 
ggcorrplot(
  type = "upper",
  hc.order = TRUE,
  outline.color = "white",
  colors = c("blue", "white", "red"),
  show.diag = TRUE) +
  scale_x_discrete(position = "top") +
  theme(
  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 10),
  axis.text.y = element_text(size = 10)) 
```

**Markowitz:**

*Weighs for the minimum variance portfolio*

```{r}
sigma <- returns_wide %>% 
  select(-date) %>% 
  cov()

u <- rep(1, dim(sigma)[1])
sigma_inv <- solve(sigma)
x_MIN <- as.vector(sigma_inv %*% u) / as.numeric(u %*% sigma_inv %*% u)
```


```{r}
assets <- assets %>% 
  mutate(x_MIN = x_MIN)

assets %>% 
  ggplot(aes(x = x_MIN,
             y = fct_reorder(symbol, x_MIN),
             fill = x_MIN > 0)) +
  geom_col() +
  labs(x = NULL,
       y = NULL) +
  theme(legend.position = "none")
```
We denote $\overline{R}$ by $R$ in what follows.


```{r}
R <- assets$mu

z_star <- sigma_inv %*% R -
  (as.numeric(u %*% sigma_inv %*% R) /
   as.numeric(u %*% sigma_inv %*% u)) *
  sigma_inv %*% u

assets <- assets %>% 
  mutate(z_star = z_star)
assets %>% 
  ggplot(aes(x = z_star,
             y = fct_reorder(symbol, z_star),
             fill = z_star > 0)) +
  geom_col() +
  labs(x = NULL,
       y = NULL) +
  theme(legend.position = "none")
```

```{r}
tau <- seq(0,0.5, by =0.001)
A <- as.numeric(u %*% sigma_inv %*% R)
B <- as.numeric(R %*% sigma_inv %*% R)
C <- as.numeric(u %*% sigma_inv %*% u)
D <- B*C-A^2

x_efc <- sapply(tau, function(tau_val) {
  x_MIN + (tau_val/2)*z_star
})

summary_min <- tibble(mu = A/C,
                      sd = sqrt(1/C),
                      type = "Minimum-Variance Portfolio")

summary_efc <- tibble(tau = tau,
                      mu = (A/C) + (tau/2)*(D/C),
                      sd = sqrt((1/C)+(tau^2/4)*(D/C)),
                      type = "Efficient Portfolio")

summaries <- bind_rows(assets, summary_min, summary_efc)
```
Now the data is ready for the efficient frontier plot:


```{r}
summaries %>% 
  ggplot() +
  geom_line(data = summary_efc, 
            aes(x = sd*sqrt(252), y = mu*252), 
            color = "steelblue") +
  
  geom_point(data = summary_min,
             aes(x = sd*sqrt(252), y = mu*252),
             color = "red",
             size = 3) +
  
  geom_path(data = summary_efc, 
            aes(x = sd*sqrt(252), y = mu*252), 
            color = "steelblue") +
  
  geom_point(data = assets, 
             aes(x = sd*sqrt(252), y = mu*252)) +
  
  geom_label(
    data = summary_min,
    aes(x = sd*sqrt(252), 
        y = mu*252, 
        label = "bold(x)^MIN"),
    parse = TRUE,
    vjust = -0.5,
    hjust = 0
  ) +
  
  scale_x_continuous(labels = scales::percent) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(-0.1, 1)) +
  
  labs(x = "Standard deviation", 
       y = "Expected return") +
  
  theme_minimal()
```

*Import of risk-free rate*
```{r}
risk_free_daily <- download_data(
  type = "stock_prices", symbol = "^IRX", 
  start_date = "2016-10-01", end_date = "2024-04-20"
) %>% 
  mutate(
    risk_free = (1 + adjusted_close / 100)^(1 / 252) - 1
  ) %>% 
  select(date, risk_free) %>%  
  drop_na()

rf <- mean(risk_free_daily$risk_free)
```


