---
title: "P4 - Application"
author: "Group M04-04"
date: "2026-04-20"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
library(tidyverse)
library(tidyfinance)
library(scales)
library(ggrepel)
library(ggcorrplot)
library(dplyr)
```

KAPITEL 1:

```{r}
#####
tickers <- c("NVDA","NXPI", "EPAM", "BRK-B", "PYPL", "FDS", "CAT", "DAL", "POOL", "AMZN", "NCLH", "CASY", "LLY", "BDX", "CRL", "GOOG", "EA", "PSKY", "WMT", "CPB", "EL", "XOM", "OXY", "APA", "LIN", "MLM", "MOS", "NEE", "ATO", "AES", "WELL", "SBAC", "ARE")
#####
prices <- download_data(type = "stock_prices",
                         symbols = tickers,
                         start_date = "2016-01-01",
                         end_date = "2024-01-01")

#####
stock_list <- prices %>%
    filter(symbol %in% tickers) %>%
    split(.$symbol)
#####
```

```{r}

#prices |>
#    ggplot(aes(x = date, y = adjusted_close)) +
#    geom_line() +
#    labs(
#        x = NULL,
#        y = NULL,
#        title = "Stock price development"
#    )

```

```{r}
returns <- prices |>
    group_by(symbol) |>
    arrange(date) |>
    mutate(ret = log(adjusted_close / lag(adjusted_close))) |>
    select(symbol, date, ret) |>
    drop_na(ret)
```

```{r}
# quantile_05 <- quantile(returns$ret, probs = 0.05)
# quantile_95 <- quantile(returns$ret, probs = 0.95)

# returns |>
#    ggplot(aes(x = ret)) +
#    geom_histogram(bins = 100) +
#    geom_vline(aes(xintercept =quantile_05),
#        linetype = "dashed") +
#    geom_vline(aes(xintercept =quantile_95),
#        linetype = "dashed") +
#    labs(
#        x = "NULL",
#        y = "NULL",
#        title = "Histogram of returns with 5% and 95% quantiles"
#    ) +
#        scale_x_continuous(labels = percent)
```

```{r}
returns |>
    summarize(across(
        ret,
        list(
            daily_mean = mean,
            daily_sd = sd,
            daily_min = min,
            daily_max = max
        )
    ))
```

```{r}
returns |>
    group_by(year = year(date)) |>
    summarize(across(
        ret,
        list(
            daily_mean = mean,
            daily_sd = sd,
            daily_min = min,
            daily_max = max
        ),
        .names = "{.fn}"
    )) |>
    print(n = Inf)
```

KAPITEL 2:

```{r}
prices_daily <- prices |>
    group_by(symbol) |>
    mutate(n = n()) |>
    ungroup() |>
    filter(n == max(n)) |>
    select(-n)
```

```{r}
returns_monthly <- prices_daily |>
    mutate(date = floor_date(date, "month")) |>
    group_by(symbol, date) |>
    summarize(price = last(adjusted_close), .groups = "drop_last") |>
    mutate(ret = price / lag(price) - 1) |>
    drop_na(ret) |>
    select(-price)
```

```{r}
assets_monthly <- returns_monthly |>
    group_by(symbol) |>
    summarize(
        mu = mean(ret),
        sigma = sd(ret)
    )
```

```{r}
assets <- returns |>
    group_by(symbol) |>
    summarize(mu = mean(ret), sigma = sd(ret))
```

```{r}
#####
assets |>
    ggplot(aes(x = sigma, y = mu, label = symbol)) +
    geom_point() +
    geom_text_repel() +
    scale_x_continuous(labels = percent) +
    scale_y_continuous(labels = percent) +
    labs(
        x = "Risk (Standard Deviation of Returns)",
        y = "Expected Return (Mean of Returns)",
        title = "Risk-Return Profile of Assets"
    )
#####
```

```{r}
returns_wide <- returns |>
    pivot_wider(names_from = symbol, values_from = ret)

sigma_c <- returns_wide |>
    select(-date) |>
    cov(use = "pairwise.complete.obs")

sigma_c |>
    ggcorrplot(
        type = "upper",
        hc.order = TRUE,
        outline.color = "white",
        color = c("blue", "white", "red"),
        show.diag = TRUE
    ) +
    scale_x_discrete(position = "top") +
    theme(
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10)
    )
```

```{r}
#####
#sigma |>
#    as_tibble(rownames = "symbol_a") |>
#    pivot_longer(-symbol_a, names_to = "symbol_b") |>
#    ggplot(aes(x = symbol_a, y =fct_rev(symbol_b), fill = value)) +
#    geom_tile() +
#    labs(
#        x = NULL,
#        y = NULL,
#        fill = "(Co-variance)",
#        title = "Covariance Matrix of Asset Returns"
#    ) +
#    scale_fill_continuous(labels = percent) +
#    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#    guides(fill = guide_colorbar(barwidth = 15, barheight = 0.5))
#####
```

```{r}
sigma <- returns_wide |>
    select(-date) |>
    cov()
```

```{r}
iota <- rep(1, dim(sigma)[1])
sigma_inv <- solve(sigma)
omega_mvp <- as.vector(sigma_inv %*% iota) / as.numeric(t(iota) %*% sigma_inv %*% iota)
```

```{r}
assets <- bind_cols(assets, omega_mvp = omega_mvp)

#####
assets |>
    ggplot(aes(x = omega_mvp, y = fct_reorder(symbol, omega_mvp), fill = omega_mvp > 0)) +
    geom_col() +
    scale_x_continuous(labels = percent) +
    labs(
        x = NULL, y = NULL, title = "Weights of Assets in the Minimum Variance Portfolio"
    ) +
    theme(legend.position = "none")
#####
```

```{r}
mu <- assets$mu

summary_mvp_ <- tibble(
    mu = as.numeric(t(omega_mvp) %*% mu),
    sigma = as.numeric(sqrt(t(omega_mvp) %*% sigma %*% omega_mvp)),
    type = "Minimum-Variance Portfolio"
)
summary_mvp_
```

```{r}
z_star <- sigma_inv %*% mu - (as.numeric(iota %*% sigma_inv %*% mu) / as.numeric(iota %*% sigma_inv %*% iota)) * sigma_inv %*% iota

assets <- assets |>
    mutate(z_star = z_star)
assets |>
    ggplot(aes(x = z_star,
              y = fct_reorder(symbol, z_star), fill = z_star > 0)) +
    geom_col() +
    labs(x = NULL,
        y = NULL) +
    theme(legend.position = "none")
```

```{r}
mu_bar <- max(assets$mu)
```

```{r}
tau <- seq(0,1, by = 0.001)
A <- as.numeric(t(iota) %*% sigma_inv %*% mu)
B <- as.numeric(t(mu) %*% sigma_inv %*% mu)
C <- as.numeric(t(iota) %*% sigma_inv %*% iota)
D <- B * C - A^2
E <- as.numeric(t(mu) %*% sigma_inv %*% mu)

lambda_tilde <- as.numeric(2 * (mu_bar - D / C) / (E - D^2 / C))
omega_efp_ <- as.vector(omega_mvp + lambda_tilde / 2 * (sigma_inv %*% mu - D * omega_mvp))

omega_efp <- sapply(tau, function(tau_val){
    omega_mvp + (tau_val / 2) * z_star
})

summary_mvp <- tibble(
    mu = A / C,
    sigma = sqrt(1 / C),
    type = "Minimum-Variance Portfolio")

summary_efp <- tibble(
    tau = tau,
    mu = (A / C) + (tau / 2) * (D / C),
    sigma = sqrt((1 / C) + (tau^2 / 4) * (D / C)),
    type = "Efficient Portfolio"
)
```

```{r}
summaries <- bind_rows(
    assets, summary_mvp, summary_efp
)
#####
summaries |>
    ggplot(aes(x = sigma, y = mu)) +
    geom_point(
        data = summaries |> filter(is.na(type))
    ) +
    geom_point(
        data = summaries |> filter(!is.na(type)), color = "#F21A00", size = 3
    ) +
    geom_label_repel(aes(label = type)) +
    scale_x_continuous(labels = percent) +
    scale_y_continuous(labels = percent) +
    labs(
        x = "Risk (Standard Deviation of Returns)",
        y = "Expected Return (Mean of Returns)",
        title = "Efficient & minimum-variance portfolios"
    ) 
```

```{r}
efficient_frontier <- tibble(
    a = seq(from = -1, to = 2, by = 0.01),
) |>
    mutate(
        omega = map(a, \(x) x * omega_efp + (1 - x) * omega_mvp),
        mu = map_dbl(omega, \(x) t(x) %*% mu),
        sigma = map_dbl(omega, \(x) sqrt(t(x) %*% sigma %*% x)),
    )
```

```{r}
summaries <- bind_rows(
    summaries, efficient_frontier
)
#####
summaries |>
    ggplot(aes(x = sigma, y = mu)) +
    geom_point(
        data = summaries |> filter(is.na(type))
    ) +
    geom_point(
        data = summaries |> filter(!is.na(type)), color = "#F21A00", size = 3
    ) +
    geom_label_repel(aes(label = type)) +
    scale_x_continuous(labels = percent) +
    scale_y_continuous(labels = percent) +
    labs(
        x = "Risk (Standard Deviation of Returns)",
        y = "Expected Return (Mean of Returns)",
        title = "Efficient frontier from tickers"
    ) +
    theme(legend.position = "none")
#####
```

KAPITEL 3:

```{r}
risk_free_daily <- download_data(
    type = "stock_prices", symbol = "^IRX",
    start_date = "2016-01-01", end_date = "2024-01-01"
) |>
    mutate(
        risk_free = (1 + adjusted_close / 100)^(1 / 252) - 1
    ) |>
    select(date, risk_free) |>
    drop_na()

rf <- mean(risk_free_monthly$risk_free)
```

```{r}
sigma <- returns |>
    pivot_wider(names_from = symbol, values_from = ret) |>
    select(-date) |>
    cov()

mu <- returns |>
    group_by(symbol) |>
    summarise(mu = mean(ret)) |>
    pull(mu)
```

```{r}
H <- rf^2 * C - 2 * rf * A + B

summary_rf <- tibble(
    tau = tau,
    rf = rf,
    mu = rf + tau / 2 * H,
    sigma = sqrt(tau^2 / 4 * H)
    type = "Risk free portfolio"
)

summaries <- bind_rows(summaries, summary_rf)
```

```{r}
w_tan <- solve(sigma) %*% (mu - rf)
w_tan <- w_tan / sum(w_tan)

mu_w <- as.numeric(t(w_tan) %*% mu)
sigma_w <- as.numeric(sqrt(t(w_tan) %*% sigma %*% w_tan))

efficient_portfolios <- tribble(
    ~symbol, ~mu, ~sigma,
    "omega[tan]", mu_w, sigma_w,
    "r[f]", rf, 0
)

sharpe_ratio_ <- (mu_w -rf) / sigma_w
```

```{r}
tau_target <- 2 / (A - rf * C)
summary_tan <- summary_efp |>
    slice_min(abs(tau - tau_target), n = 1) |>
    select(tau, mu, sigma) |>
    mutate(type = "Tangency portfolio") |>
    as_tibble()

summaries <- bind_rows(summaries, summary_tan)

tangency_portfolio <- as.numeric((sigma_inv %*% (mu - rf * iota)) / (A - rf * C))

sharpe_ratio <- as.numeric((tangency_portfolio %*% mu - rf) / sqrt((tangency_portfolio %*% sigma %*% tangency_portfolio)))
```

```{r}
assets <- assets %>% 
  mutate(tangency_portfolio = tangency_portfolio)
assets %>% 
  ggplot(aes(x = tangency_portfolio,
             y = fct_reorder(symbol, tangency_portfolio),
             fill = tangency_portfolio > 0)) +
  geom_col() +
  labs(x = NULL,
       y = NULL) +
  theme(legend.position = "none")
```

```{r}
#####
assets |>
    ggplot(aes(x = sigma, y = mu)) +
    geom_point() +
    geom_point(data = efficient_portfolios, color = "blue") +
    geom_label_repel(data = efficient_portfolios, aes(label = symbol), parse = TRUE) +
    scale_x_continuous(labels = percent) +
    scale_y_continuous(labels = percent) +
    labs(
        x = "Risk", y = "Expected return",
        title = "The efficient frontier with a risk-free asset"
    ) +
    geom_abline(aes(intercept = rf, slope = sharpe_ratio_), linetype = "dotted")
#####
```

```{r}
betas <- (sigma %*% w_tan) / as.numeric(t(w_tan) %*% sigma %*% w_tan)
assets <- assets |>
    mutate(beta = betas)

price_of_risk <- as.numeric(t(w_tan) %*% mu - rf)
#####
assets |>
    ggplot(aes(x = beta, y = mu)) +
    geom_point() +
    geom_abline(intercept = rf, slope = price_of_risk) +
    scale_y_continuous(labels = percent) +
    labs(
        x = "Beta", y = "Expected return",
        title = "Security market line"
    ) + 
    annotate("text", x = 0, y = rf, label = "Risk-#free")
#####
```

```{r}
factors <- download_data(
    type = "factors_ff_5_2x3_monthly",
    start_date = "2016-01-01", end_date = "2024-01-01"
) |>
    select(date, mkt_excess, risk_free)
```

```{r}
returns_excess_monthly <- returns_monthly |>
    left_join(factors, join_by(date)) |>
    mutate(ret_excess = ret - risk_free) |>
    select(symbol, date, ret_excess, mkt_excess)

estimate_capm <- function(data) {
    fit <- lm("ret_excess ~ mkt_excess", data = data)
    tibble(
        coefficient = c("alpha", "beta"),
        estimate = coefficients(fit),
        t_statistic = summary(fit)$coefficients[, "t value"]
    )
}

capm_results <- returns_excess_monthly |>
    nest(data = -symbol) |>
    mutate(capm = map(data, estimate_capm)) |>
    unnest(capm) |>
    select(symbol, coefficient, estimate, t_statistic)
```

```{r}
#####
capm_results |>
    filter(coefficient == "alpha") |>
    mutate(is_significant = abs(t_statistic) >= 1.96) |>
    ggplot(aes(x = estimate, y = fct_reorder(symbol, estimate), fill = is_significant)) +
    geom_col() +
    scale_x_continuous(labels = percent) +
    labs(
        x = "Estimated asset alphas", y = NULL, fill = "Significant at 95%?",
        title = "Estimated CAPM alphas"
    )
```

```{r}
sp500 <- download_data(type = "stock_prices", 
                       symbols = "^GSPC",
                       start_date = "2016-01-01",
                       end_date = "2024-01-01")
market_returns <- sp500 %>% 
  arrange(date) %>% 
  mutate(market_ret = log(adjusted_close/lag(adjusted_close))) %>% 
  select(date, market_ret) %>% 
  drop_na()
data_capm <- returns %>% 
  left_join(market_returns, by = "date") %>% 
  mutate(excess_ret = ret - rf,
         market_excess = market_ret - rf)

betas <- data_capm %>% 
  group_by(symbol) %>% 
  summarise(beta = (cov(ret,market_ret))/var(market_ret))

market_R <- mean(market_returns$market_ret)
sml <- betas %>% 
  mutate(expected_capm = rf + beta*(market_R-rf))

assets_smlplot <- assets %>% 
  select(symbol, mu, sigma)
assets_smlplot <- assets_smlplot %>% 
  left_join(sml, by = "symbol")
```

```{assets_smlplot %>%}
  ggplot() +
  geom_line(data = assets_smlplot,
            aes(x = beta,
                y = expected_capm*252)) +
  geom_point(data = assets_smlplot,
             aes(x = beta,
                 y = mu*252)) +
  geom_label_repel(data = assets_smlplot,
                   aes(x = beta,
                       y = mu*252,
                       label = symbol),
                       size = 3,
                       box.padding = 0.3,
                       point.padding = 0.2,
                       max.overlaps = Inf) +
  geom_abline(intercept = rf*252, slope = (market_R-rf)*252, color = "steelblue") +
  scale_y_continuous(labels = percent,
                     breaks = breaks_width(0.1)) +
  labs(x = "Beta",
       y ="Expected yearly return") +
  theme_minimal() +
  theme(legend.position = "none") {r}
```